# Generated by Django 4.2.3 on 2023-07-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="profile_pic",
            field=models.ImageField(default="default.png", upload_to="pictures"),
        ),
    ]
