# Generated by Django 4.2.3 on 2023-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_newuser_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="profile_pic",
            field=models.ImageField(default="default.jpg", upload_to="pictures"),
        ),
    ]
