# Generated by Django 4.2.3 on 2023-07-10 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="pic",
        ),
    ]
